### ISSUE TITLE
How to use multiple modules with new template?

### ISSUE THREAD

**Issue by kolkov** [ui-router/quickstart-ng2#11]
Hi!
How to use multiple modules with this template properly?
For example:
FooModule,
BarModule,
CommonModule?

**Comment by kolkov** [comment]
As a result:
Error: Error: Type UISref is part of the declarations of 2 modules: PublicModule and AppModule!(…)

**Comment by christopherthielen** [comment]
I'm working on first class NgModule support in beta.2, please stay tuned.

**Comment by kolkov** [comment]
Thank you! Will be glad to test in the forefront!

**Comment by kolkov** [comment]
I've submitted a pull request with updated modules to 1.0.0-beta.2, check it out, please.

**Comment by christopherthielen** [comment]
quickstart now has multiple modules `FooModule`, `BarModule`, `BazModule` where `BazModule` is lazy loaded

**Comment by kolkov** [comment]
Super! )
