### ISSUE TITLE
lazyLoad error.

### ISSUE THREAD

**Issue by kolkov** [ui-router/quickstart-ng2#15]
Trying to run quickstart-ng2 from that branch:

![image](https://cloud.githubusercontent.com/assets/3740898/18257187/7dd5d5da-73c8-11e6-8284-416eacfa4e3c.png)

**Comment by kolkov** [comment]
We need change [this line](https://github.com/ui-router/quickstart-ng2/blob/rc5compat/src/baz/baz.module.ts#L2):
`import {CommonModule} from "../common.module";`
to
`import {CommonModule} from "@angular/common";`

**Comment by kolkov** [comment]
Maybe we need change name CommonModule to RootModule or CoreModule?

**Comment by christopherthielen** [comment]
Renamed it to `SharedModule`  👍
