### ISSUE TITLE
core.umd.js:3462 EXCEPTION: Uncaught (in promise): TransitionRejection(type: 2, message: The transition has been superseded by a different transition, detail: 'app.baz'{})

### ISSUE THREAD

**Issue by kolkov** [ui-router/quickstart-ng2#19]
After clicking to 'buz' link:
![image](https://cloud.githubusercontent.com/assets/3740898/18607784/c1a50dce-7cdf-11e6-97a1-e578e79d2d0f.png)

**Comment by christopherthielen** [comment]
I tracked this down to the transition visualizer and "makeCancelablePromise". Should have a fix shortly.

**Comment by kolkov** [comment]
Thanks! Fixed now!
