### ISSUE TITLE
upgrade to use ng2.rc1

### ISSUE THREAD

**Issue by earlyster** [ui-router/quickstart-ng2#2]
I tried to upgrade to RC1 but looks like ui-router version 1.0.0-alpha.5 is not out yet

**Comment by earlyster** [comment]
I did a first pass (manually copied npm module) 
https://github.com/earlyster/quickstart-ng2/commit/2fc06a30dbc676dbfb46fc32d007ecd15aee6b07

There are some issues with README still didn't resolve those conflicts.

**Comment by christopherthielen** [comment]
Thanks for that!! I have already updated QuickStart in a local branch. Will push as soon as alpha.5 lands. 

Alpha.5 is blocked on html5 push state support. If that doesn't happen before Friday ill release .5 without push state. 

I wish I had more time... Apologies.

**Comment by earlyster** [comment]
No problem thanks for quick reply

**Comment by earlyster** [comment]
Hi @christopherthielen are there instructions to build the ui-router-ng2 npm module so I can just use it locally and link to it... I tried using ui-router build but couldn't figure out where the module was created.

**Comment by christopherthielen** [comment]
@earlyster run `./scripts/package.js ng2` then your built package will be in `build_packages/ng2`

**Comment by christopherthielen** [comment]
@earlyster also, I plan to release alpha.5 very soon (later today?)

**Comment by christopherthielen** [comment]
alpha.5 released, and quickstart-ng2 updated

**Comment by earlyster** [comment]
Thx

**Comment by christopherthielen** [comment]
Somebody on gitter said there is a problem with the QuickStart. Going to
look into it in the morning.

**Comment by christopherthielen** [comment]
quickstart is fixed (had to pin the rxjs dependency)
