### ISSUE TITLE
can someone adress this issue?

### ISSUE THREAD

**Issue by ishandutta2007** [ui-router/quickstart-ng2#22]
http://stackoverflow.com/questions/37408620/angular-2-rc1-address-line-bug

I am facing the same problem.
I haven't made any changes either .
Functionality wise everything works as expected, but on the address-bar it's showing a wrong url.
Secondly, except crisis-center none of the other URI is directly accessible from address bar

**Comment by christopherthielen** [comment]
I think you want https://github.com/angular/angular/issues
