### ISSUE TITLE
 Object literal may only specify known properties, and 'configClass' does not exist in type 'RootModule'.

### ISSUE THREAD

**Issue by mizi-lin** [ui-router/quickstart-ng2#28]
> ui-router-ng2-quickstart@1.0.4 tsc /Users/Mizi/git/quickstart-ng2
> tsc

src/bootstrap.ts(27,7): error TS2345: Argument of type '{ states: Ng2StateDeclaration[]; otherwise: { state: string; params: {}; }; useHash: true; config...' is not assignable to parameter of type 'RootModule'.
  Object literal may only specify known properties, and 'configClass' does not exist in type 'RootModule'.

**Comment by liangtongxie** [comment]
+1

**Comment by Asone** [comment]
+1

**Comment by Asone** [comment]
you can still make the quickstart work changing ui-router version to 1.0.0-beta3. 

Go to your package.json and replace : 

    "ui-router-ng2": "^1.0.0-beta.3"

with 

    "ui-router-ng2": "1.0.0-beta.3"

Then run npm install to update the version. It should work

**Comment by Asone** [comment]
found this in the changelog.md of ui-router-ng2 : 

## BREAKING CHANGE: You no longer configure a module using an Injectable `UIRouterConfig` class. Now you use a function that receives the `UIRouter` and the `Injector`

In 1.0.0-beta.3 you might have a config class like this:
```js
export class MyUIRouterConfig {
  constructor(@Inject(UIRouter) router: UIRouter, @Inject(SomeService) myService: SomeService) {
    // do something with router and injected service
  }
}

which was wired into the root module like this:
```js
@NgModule({
  imports: [
    UIRouterModule.forRoot({ configClass: MyUIRouterConfig })
  ]
})
export class AppModule {}
```

In 1.0.0-beta.4 you should switch to a simple function.
The function receives the router: `UIRouter` and injector: `Injector`
```js
export function configureModule(router: UIRouter, injector: Injector) {
  // do something with router
  router.urlService.rules.type('slug', slugParamType);
  // inject other services
  const myService: SomeService = injector.get(SomeService);
  // do something injected service
  myService.init();
}
```

which is now wired using `config: configureModule` instead of `configClass: ...`
```js
@NgModule({
  imports: [
    UIRouterModule.forRoot({ configClass: MyUIRouterConfig })
  ]
})
export class AppModule {}
```

**Comment by christopherthielen** [comment]
Yep, the configClass wasn't working nicely with angular DI.  Instead, just pass a function as `config: configFn` which will receive the UIRouter instance.
