### ISSUE TITLE
Update with ^4.0.0 Angular 2 version

### ISSUE THREAD

**Issue by Asone** [ui-router/quickstart-ng2#30]
Check possibility for updating the demo with the latest release of Angular 2? 

I'll update comment step by step, yet for now, using the last version doesn't spit any error but the view after init does not update.

**Comment by christopherthielen** [comment]
I updated it t Angular 4

Note: I won't be maintaining this quickstart.  Instead, I'd like to have a quickstart which uses the angular-cli
