### ISSUE TITLE
UI router ng2 not working for ng4 - which is backward compatible?!

### ISSUE THREAD

**Issue by moorthi07** [ui-router/quickstart-ng2#32]
```
"dependencies": {
    "@angular/animations": "^4.0.2",
    "@angular/common": "^4.0.2",
    "@angular/compiler": "^4.0.2",
    "@angular/compiler-cli": "^4.0.2",
    "@angular/core": "^4.0.2",
    "@angular/forms": "^4.0.2",
    "@angular/http": "^4.0.2",
    "@angular/material": "^2.0.0-beta.3",
    "@angular/platform-browser": "^4.0.2",
    "@angular/platform-browser-dynamic": "^4.0.2",
    "@angular/platform-server": "^4.0.2",
    "@angular/router": "^4.0.2",
    "typescript": "^2.2.2",
    "ui-router-ng2": "^1.0.0-beta.4",
    "zone.js": "^0.8.5"
```

 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\ch
okidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@
1.1.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"}
)
npm WARN ng2-restangular@0.1.30 requires a peer of @angular/core@^2.0.0 but none
 was installed.
npm WARN ng2-restangular@0.1.30 requires a peer of @angular/platform-browser@^2.
0.0 but none was installed.
npm WARN ng2-restangular@0.1.30 requires a peer of @angular/http@^2.0.0 but none
 was installed.
npm WARN @angular/core@2.4.10 requires a peer of zone.js@^0.7.2 but none was ins
talled.
npm WARN @angular/platform-browser@2.4.10 requires a peer of @angular/common@2.4
.10 but none was installed.
npm WARN ui-router-ng2@1.0.0-beta.4 requires a peer of @angular/common@^2.3.1 bu
t none was installed.
npm WARN ui-router-ng2@1.0.0-beta.4 requires a peer of @angular/core@^2.3.1 but
none was installed.
npm WARN ui-router-ng2@1.0.0-beta.4 requires a peer of @angular/router@^3.3.1 bu
t none was installed.
.....................................

ERROR in Error encountered resolving symbol values statically. Only initialized variables
and constants can be referenced because the value of this variable is needed by the templa
te compiler (position 15:22 in the original .ts file), resolving symbol ROUTES in D:/.............s/node_modules/@angular/router/src/router_config_loader.d.ts, resolving sy
mbol makeRootProviders in D:/..............s/node_modules/ui-router-ng2/lib/uiRoute
rNgModule.d.ts, resolving symbol UIRouterModule.forRoot in D:/...................s/node_
modules/ui-router-ng2/lib/uiRouterNgModule.d.ts, resolving symbol AppModule in D:/................s/src/app/app.module.ts, resolving symbol AppModule in D:/..............s/src/app/app.module.ts

ERROR in ./~/ui-router-ng2/lib/uiRouterNgModule.js
Module not found: Error: Can't resolve '@angular/router/src/router_config_loader' in 'D:\,,,,,,s\node_modules\ui-router-ng2\lib'
 @ ./~/ui-router-ng2/lib/uiRouterNgModule.js 6:0-66
 @ ./~/ui-router-ng2/lib/index.js
 @ ./src/app/app.module.ts
 @ ./src/app/index.ts
 @ ./src/main.ts

**Comment by Asone** [comment]
It work up to the latests minor versions of angular 2. angular 4 is still in development. 
Try switching angulars deps to ^2.4.0. 

see #31

**Comment by efistasija** [comment]
Hi @Asone, any news on when there will be a ui-router for angular 4?

**Comment by Asone** [comment]
@efistasija : I have no idea, i'm not part of the original team. I just suggested a PR a few months ago to update a bit the demo, that's mainly all. 

Apparently there's chances that this demo will be abandoned according to the comments on this page : #26

**Comment by aeternusrahl** [comment]
https://github.com/ui-router/angular/releases/tag/1.0.0-beta.6 works with ng 4.1.3

**Comment by christopherthielen** [comment]
latest beta.6 release is compatible with Angular 4

Note: The package `ui-router-ng2` has been renamed to `@uirouter/angular`

This demo will likely be replaced by something involving the Angular-CLI
