### ISSUE TITLE
Upgrade to Angular 2 rc.5

### ISSUE THREAD

**Issue by demisx** [ui-router/quickstart-ng2#7]
Angular 2 RC.5 has changed a few things around introducing a bunch of breaking changes. Currently, it represents the expected public API of the 2.0 release according to the Angular dev team. Would be very helpful to have this Quickstart UI Router app upgraded to support the ngModule based rc.5 release.

**Comment by christopherthielen** [comment]
Yep, I'm working on it.  rc.5 introduced some breaking changes for ui-router (also totally changed how apps should be bootstrapped)

**Comment by demisx** [comment]
Thank you for excellent news Chris. :+1: We are refactoring our rc.4 app as well.

**Comment by kolkov** [comment]
Hi! Thank you for your work, @christopherthielen 
I was started my new big project on Angular1 and ui-router one month ago, but now I'm trying to completely rewrite it on Angular2 and ui-router-ng2. 
I look forward to updates!

**Comment by demisx** [comment]
@christopherthielen Any rough ETA on this? Don't mean to rush, just trying to get an idea for some internal planning. Thank you for all your excellent work.

**Comment by christopherthielen** [comment]
Before next Friday; hopefully sooner

**Comment by reyramos** [comment]
I've submitted a pull request with updated module to RC5, check it out

**Comment by reyramos** [comment]
Provided a webpack example forked from this repo, thanks for the quickstart.

**Comment by christopherthielen** [comment]
@reyramos thanks for PR.  

There are some major changes for ui-router-ng2 bootstrap coming soon because of `NgModule`!

**Comment by christopherthielen** [comment]
ui-router 1.0.0-beta.2 is released with `NgModule` support.

https://github.com/ui-router/quickstart-ng2/blob/2997ec4baa263e5b37881d5e6dbdbb1f589da384/src/app.module.ts#L12-L43

Lazy loading of `NgModule` is now supported.  See:
- https://github.com/ui-router/quickstart-ng2/blob/2997ec4baa263e5b37881d5e6dbdbb1f589da384/src/app.states.ts#L10-L11
- https://github.com/ui-router/quickstart-ng2/blob/2997ec4baa263e5b37881d5e6dbdbb1f589da384/src/baz/baz.module.ts#L1-L10

**Comment by demisx** [comment]
Thank you so much for upgrading to the latest Angular 2 rc6!
